### ISSUE TITLE
How to define a symbol that can be expanded in lines?

### ISSUE THREAD

**Issue by XingweiLin** [googleprojectzero/domato#26]
Hi,

"=" symbol is different in basic syntax and lines syntax.
In basic syntax, the left symbol will be expanded by the right symbol.
But in lines syntax, it's just an equal symbol instead of expanding the left symbol.

If there exists some way that we can define symbols that can be expanded in lines instead of ending up in the output?

For example, I have a recursion expression in lines, which will new variables, the number of variables is according to the recursion depth. And I need basic syntax's "=" to define the recursion expression, but I also need the "new" features in lines syntax. So I may need some way that domato can define a symbol that can be expanded in lines instead of outputting it.

Or this problem can be solved by other ways?

**Comment by ifratric** [comment]
Hi, can you give an example of what you're trying to do?

**Comment by XingweiLin** [comment]
According to @ifratric 
The problem can be solved by enabling the 'new' attribute usable outside code lines.
We can change the line [https://github.com/googleprojectzero/domato/blob/master/grammar.py#L470]
to just ` elif 'new' in part:`
